### ISSUE TITLE
thetaphi jenkins RSS feed broken

### ISSUE THREAD

**Issue by hossman** [hossman/jenkins-reports#1]
there's not much i can do about this, but it's been a problem long enough that i felt like i should create an issue just to track/link to all of the going-ons...

First noted and mentioned via email...
http://mail-archives.apache.org/mod_mbox/lucene-dev/201908.mbox/%3Calpine.DEB.2.11.1908070946190.7306@tray%3E

Subsequent response from Uwe...
http://mail-archives.apache.org/mod_mbox/lucene-dev/201908.mbox/%3c010b01d551d0$6ae88b50$40b9a1f0$@thetaphi.de%3e

jenkins jira uwe initially identified as related...
https://issues.jenkins-ci.org/browse/JENKINS-58595
PR for that jira: jenkinsci/jenkins#4148

After uwe's jenkins was upgraded to the "fixed" version, the RSS feed was still broken, but in a diff way...
http://mail-archives.apache.org/mod_mbox/lucene-dev/201908.mbox/%3Cf51d69272cb848a90df7a279d481fe1e.squirrel%40mail.sd-datasolutions.de%3E

new jenkins jira created by Uwe regarding this change in bug...
https://issues.jenkins-ci.org/browse/JENKINS-59167
PR for that jira: jenkinsci/jenkins#4188

**Comment by uschindler** [comment]
Seems fixed with today's update: https://jenkins.thetaphi.de/view/Lucene-Solr/rssAll

**Comment by hossman** [comment]
woot!
